### ISSUE TITLE
Increase api retrieval limit to more than 10,000

### ISSUE THREAD

**Issue by sujaikumar** [genomehubs/goat-api#7]
As suggested by @rjchallis

> set max_result_window in goat.yaml (alternatively hardcode higher value, or use PUT to update after indexing). May also be worth implementing a scrolling option in case results get really big.

**Comment by rjchallis** [comment]
Added scrolling option in [42397b9](https://github.com/genomehubs/goat-api/commit/42397b9ebb2ea99e084ecf39dd5034f9fb96592d) to support large results
